# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    environment: development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2x
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: ap-southeast-1
    - name: Deploy to Aws EC2
      run: |
        aws deploy create-deployment \
        --application-name codedeploy-example-as-app \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --deployment-group-name codedeploy-example-as-depgrp \
        --description "Push to main auto deploy" \
        --github-location repository=$GITHUB_REPOSITORY,commitId=$GITHUB_SHA
        
